### ISSUE TITLE
[Bug] Lost focus on a big project

### ISSUE THREAD

**Issue by ChuxMan** [FPGAwars/icestudio#176]
When you are in a big project 

![image](https://user-images.githubusercontent.com/17034017/31859815-daa32b3c-b710-11e7-977b-e10af97cb114.png)

and zoom in on a bottom corner, 

![image](https://user-images.githubusercontent.com/17034017/31859821-009445e2-b711-11e7-902a-34b8e39741af.png)

and then you zoom out on the top

![image](https://user-images.githubusercontent.com/17034017/31859827-1417fb86-b711-11e7-93e2-c760fc92926e.png)

you lost the focus of the top of the project, and is no longer accessible

Again, tested in mac, not other platforms.

**Comment by ChuxMan** [comment]
I miss a photoshop navigator-like to move on the project or something similar. Why not scrollbars?

**Comment by Jesus89** [comment]
Hi @ChuxMan:

The zoom behavior is the same than Inkscape. The zoom point is the cursor. The issue here is that the scrollbars shouldn't be here. Btw, what version of MacOS are you using?

You can move the background with Ctrl + L mousedown or R mousedown. And also select Edit > Fit content (Ctrl+1) to center and scale the design (this also happens when the window is resized). You can check the shortcuts here: https://github.com/FPGAwars/icestudio/wiki#mouse.

By now everyone is uploading its own blocks in personal repositories. You can create an Icestudio Collection (https://github.com/FPGAwars/icm) and share your repo in the group.

**Comment by cavearr** [comment]
Fixed on v5.1.0 dev branch
