### ISSUE TITLE
Windows Install zip extract - Error 0x80070057: The parameter is incorrect

### ISSUE THREAD

**Issue by gojimmypi** [FPGAwars/icestudio#291]
while copying files from [the windows install zip](https://github.com/FPGAwars/icestudio/releases/download/v0.4.0-dev/icestudio-0.4.0-dev-win32.zip) ...

I encountered this error at the 99% mark. Googling it seems to indicate this error usually occurs during some sort of Office install. I don't have Office installed, and I was only trying to copy the files from the zip to a directory. Anti-virus has nothing in the history and did not complain
![image](https://user-images.githubusercontent.com/13059545/50385512-19143200-06d7-11e9-9f8e-cf35744bf9c8.png)

![image](https://user-images.githubusercontent.com/13059545/50385464-4ad8c900-06d6-11e9-9ea5-b3819d6e6678.png)

edit: I confirmed downloading the zip a second time, extracting to a new directory, gives the same error. 
Other problem files:
![image](https://user-images.githubusercontent.com/13059545/50385845-8ffff980-06dc-11e9-8c55-33647c60fcbd.png)

![image](https://user-images.githubusercontent.com/13059545/50385847-99896180-06dc-11e9-92ba-6fc2375b90e2.png)

![image](https://user-images.githubusercontent.com/13059545/50385851-a443f680-06dc-11e9-96c4-3afaf49177e6.png)

**Comment by camerondm9** [comment]
This error occurs because of the colons in the names of those specific files. Windows doesn't allow colons in the name of a file, but its' default ZIP extractor isn't smart enough to replace them with an alternate character.
I extracted the files successfully using [7Zip](https://www.7-zip.org/), which replaced the colons with underscores. Other ZIP extractors might do something similar...

**Comment by cavearr** [comment]
fixed on v5.1.0
