### ISSUE TITLE
Error libusb_open en debian 9 tarjeta Alhambra II

### ISSUE THREAD

**Issue by avlixa** [FPGAwars/icestudio#318]
Hola,
He instalado icestudio en debian 9 y al intentar cargar un código de prueba me da el error
ftdi_usb_get_strings failed: - 4 ( libusb_open() failed)

He visto este error documentado para windows 10 pero no encuentro nada para debian.  En windows 10 la placa me funciona bien.

También me he dado cuenta que al actualizar la toolchain siempre me dice que no coincide, desconozco si tiene algo que ver.

Saludos.
![Screenshot_20190419_101254](https://user-images.githubusercontent.com/42622894/56415224-67080380-628d-11e9-97b9-1f92974d1a9f.png)
![Screenshot_20190419_095328](https://user-images.githubusercontent.com/42622894/56415226-68393080-628d-11e9-9781-960e4364a1bc.png)

**Comment by JuanMiguelTorre** [comment]
Hola, a mi me ocurre lo mismo lo único que con la iCEstick Evaluation Kit.

**Comment by myzinsky** [comment]
same problem on macOS

**Comment by LBertrandDC** [comment]
Hello, I just noticed the same on Windows 10 Enterprise (what my college installs on staff computers). 
Using 0.7.1w202108130708

Running the lsftdi.exe binary directly from PowerShell:
>  PS C:\Users\Louis\\.icestudio\apio\packages\tools-oss-cad-suite\bin> .\lsftdi.exe
>  Number of FTDI devices found: 1
>  Checking device: 0
>  ftdi_usb_get_strings failed: -4 (libusb_open() failed)

The problem might caused by pilot error. When the Zadig driver utility appears, there are several choices of USB devices and the user (me!) did not select "Lattice FTUSB Interface Cable (Interface 0)". I can't remember because I wasn't paying attention to that detail.
I ran
> apio drivers --ftdi-enable

from the venv under .icestudio in the home directory/folder and that seems to have corrected the problem.
Also, it helps if you unplug as many USB devices as possible to shorten the list of devices.

**Comment by Obijuan** [comment]
Could you please try the lates Icestudio wip? You can download it from here:

https://downloads.icestudio.io/

I am cleaning old issues. I will close this issue. Please, feel free to open a new one with updated information if the error remains
Thanks for the feedback

**Comment by LBertrandDC** [comment]
Hi @Obijuan, I can program the Lattice iCEstick, no problems, using either WIP snapshot from today 0.9.2w20220502{0505|0905}
Also, random fact if that helps, I tried (from the Zadig utility) the WinUSB driver and it also worked.

**Comment by Obijuan** [comment]
Great! Thanks for the feedback 🙂️
