### ISSUE TITLE
[Dev-0.5.1n201120] Conversion window does not get closed

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/icestudio#456]
When an example is loaded from the default collection, there appear a windows for converting the example to your board or load as it is. But that windows is never closed, and it is not possible to work with the example

In this animation is shown how to reproduce the bug

![Peek 2020-11-21 07-51](https://user-images.githubusercontent.com/1286062/99869893-ee86c880-2bce-11eb-95d9-63afe2bd9523.gif)

* Icestudio version: nightly 0.5.1n201120
* Operating system: Ubuntu 20.04

**Comment by cavearr** [comment]
Fixed error, icestudio can't create the build dir folder (new feature) and hangs. 

Only affect to linux because appImage create a virtual mount point in only read mode.

Is fixed yet, now, when Icestudio can't create the build dir folder in the .ice folder, create it in old way at the os temporal directory.

This issue is the same that #457 

Stay open until you confirm it works

**Comment by Obijuan** [comment]
Checked! It works! 😀️  Thanks a lot!
