### ISSUE TITLE
MacOSX Nightly Toolchain installation stalls in `apio install icesprog` step

### ISSUE THREAD

**Issue by undo76** [FPGAwars/icestudio#475]
I'm trying to install the latest Nightly version but it fails while installing the toolchain. 
I have tried to reinstall it from scratch several times with no success. The stable version is working properly.

![image](https://user-images.githubusercontent.com/1415667/103308323-7c49a500-4a12-11eb-84b1-f28abc187154.png)

As I understand the IceSugar support is not available in MacOSX, so maybe it shouldn't try to even download it at all.

**Comment by Obijuan** [comment]
There is a bug in icestudio 201120 that prevents it from installing the latest toolchain. It has been already fixed in the development version but the new binaries has not already been created

As a workaround, I've make a quick patch to apio: the version number is lowered to 0.5.99 and now it should installs ok

Please update the toolchain again (from your icestudio 201120). After the upgrade, you should see apio 0.5.99 in Tools/Toolchain

Waiting for your new feedback. Thanks for your help

**Comment by undo76** [comment]
The workaround is working properly. Thanks a lot for your prompt response!

**Comment by Obijuan** [comment]
Great! 😀️ Thanks for the Feedback
