### ISSUE TITLE
icestudio couldn't upload successfully to Lattice iCE40-HX8K Breakout Board in Ubuntu 22.04

### ISSUE THREAD

**Issue by tony467913** [FPGAwars/icestudio#661]
Hello,

I bought a Lattice iCE40-HX8K Breakout Board a couple of days ago.
and followed the installation wiki to install icestudio on my Ubuntu 22.04.1 LTS
![Screenshot from 2022-11-15 22-22-04](https://user-images.githubusercontent.com/22197100/201949808-2bc14c9c-d00f-4be1-bf2d-9c5547161c9e.png)

but having a problem trying to upload example code "One LED" to the FPGA.
but no matter how I tried, the board always showed "board not connected" when I clicked upload.
![Screenshot from 2022-11-15 22-51-53](https://user-images.githubusercontent.com/22197100/201950981-d3a6601d-c6c8-4d52-9fb1-c48762650fb4.png)

Tried with enable driver. and reconnect the FPGA board.
![Screenshot from 2022-11-15 22-52-09](https://user-images.githubusercontent.com/22197100/201951156-d7fb8015-2400-4705-8beb-70d2e73becec.png)
  
kernel message when plugging in the FPGA board. 
![Screenshot from 2022-11-15 22-53-09](https://user-images.githubusercontent.com/22197100/201951593-25ceeda3-aa5a-401a-97c2-3e56f55a2679.png)

Operation screencast
https://youtu.be/HmGkcLRkr_0

**Comment by cavearr** [comment]
Hi tony! i'm charliva in FPGAWars community, i'm reply you at our forum:

https://groups.google.com/g/fpga-wars-explorando-el-lado-libre/c/cEK8LXd_iu8/m/pv3Te4UlBAAJ?utm_medium=email&utm_source=footer

Continue there with this issue because in this forum there are more people that could help you in this issue.

I'm closing here and continue in Google groups .
