### ISSUE TITLE
Selección de componentes a vista de pájaro.

### ISSUE THREAD

**Issue by Democrito** [FPGAwars/icestudio#785]
En circuitos un poco grandes o con muchos componentes, al intentar seleccionar con el ratón una zona (shift + manteniendo pulsado el botón izquierdo del ratón), se agregan componentes que no pertenece a esa área, normalmente los que están más arriba. Este problema desaparece al hacer un poco de zoom, entonces todo se seleccionar correctamente.

![seleccion de componentes a vista de pajaro](https://github.com/user-attachments/assets/793c2906-105e-46a7-85ea-010e4e30464e)

**Comment by cavearr** [comment]
Resuelto en la última WIP https://downloads.icestudio.io

Cuando puedas verificarlo prefiero que cierres tú la issue para hacer doble ckeck (mío y tuyo).

Gracias!

**Comment by jojo535275** [comment]
Same Little remark: i am still on version 0.11.3W202406110606
and this problem was already present on thaht version!

and it doesn't make a difference if we:
-start the box on a top-left corner than move to bottom-rigtht direction
-or start the box on a bottom-rigtht corner than move to  top-left direction 

i will later update my icestudio version and check again!

**Comment by Democrito** [comment]
Ya trabaja bien la selección de componentes en la última wip.
